desmotivacional_messages = [
    "Não importa o quanto você tente, às vezes a vida só não dá certo.",
    "A única coisa que você ganha tentando é mais frustração.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Você pode ser qualquer coisa que queira, desde que não queira ser nada.",
    "Quanto mais você corre atrás, mais o fracasso te alcança.",
    "Às vezes o melhor caminho é o mais fácil: não fazer nada.",
    "Tente de novo… ou não. A escolha é sua, mas quem se importa?",
    "O esforço não garante resultados. Na verdade, ele só garante cansaço.",
    "Nada como um bom fracasso para te lembrar de que nada na vida é garantido.",
    "O sucesso é só uma questão de perspectiva... de quem não está tentando.",
    "Se você não falhou, é porque ainda não tentou o suficiente.",
    "O objetivo é chegar ao final do dia sem mais problemas do que os que você começou.",
    "Sonhar é para quem tem tempo. Trabalhar é para quem tem energia.",
    "A vida é curta, e o fracasso é mais curto ainda.",
    "Na corrida da vida, você provavelmente vai tropeçar no seu próprio destino.",
    "A persistência só funciona quando você tem algo para alcançar. Caso contrário, é só desgaste.",
    "Fracassar é só o começo… e depois vem a parte de desistir.",
    "A vida te dá limões, mas quem se importa? Você não vai fazer nada com eles.",
    "A sorte não existe, mas o fracasso… ah, esse é garantido.",
    "Não se preocupe, o fracasso é uma das poucas coisas que nunca falta.",
    "Por que tentar algo novo, se o que já não deu certo também pode ser tentado de novo?",
    "O esforço é a chave do fracasso. Relaxar é a chave da mediocridade.",
    "Tudo vai dar errado, e isso é perfeitamente normal.",
    "O único limite para o seu fracasso é o seu desejo de tentar.",
    "Nada nunca sai como planejado, então planeje falhar de uma vez.",
    "O fracasso é apenas a prova de que você se importou o suficiente para tentar.",
    "Quando a vida lhe der oportunidades, ignore-as. Assim o fracasso vem mais rápido.",
    "A persistência é só um jeito elegante de continuar perdendo.",
    "Tente, falhe, tente de novo… mas a diferença é que você não vai conseguir mesmo assim.",
    "No final das contas, ninguém se importa com o quanto você tentou."
]
